# Generated by Django 2.2 on 2019-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_bookmarked_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('S', 'seller'), ('B', 'buyer')], default=123123, max_length=1),
            preserve_default=False,
        ),
    ]
