# Generated by Django 2.2.2 on 2019-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ReportAdvertisement',
        ),
    ]
